name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - run: |
          go vet ./...
          go test ./... --cover
      - name: Install license check tool
        run: go install github.com/google/addlicense@b289835c0741ba2fb92dd5f61af070e79c69a55e # v1.2.0
      - name: Check licenses
        run: addlicense -l apache -check -v -ignore '**/*.yaml' -c 'The Score Authors' ./formatter ./framework ./loader ./schema ./types ./uriget
